---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart kewlchats workers
  ansible.builtin.systemd_service:
    name: "{{ app_name }}-worker.service"
    state: restarted
    daemon_reload: true
